language: node_js
sudo: false
node_js:
- '5.4.1'

addons:
  firefox: latest

cache:
  directories:
    - node_modules

env:
  global:
  - ARCH=linux-x64

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./node_modules/.bin/karma start --single-run --browsers Firefox

notifications:
  webhooks:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
