language: node_js
sudo: false
node_js:
  - 5.4.1

addons:
  firefox: latest

cache:
  directories:
    - node_modules

env:
  global:
  - ARCH=linux-x64

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./node_modules/.bin/karma start --single-run --browsers Firefox

notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false

deploy:
  - provider: gae
    keyfile: Houston-be1666ecca81.json
    project: houston-1197
    default: true
    on:
      repo: angular/answers-app

after_success:
  - '[[ $TRAVIS_PULL_REQUEST = "false" ]] && [[ $TRAVIS_BRANCH = "master" ]] && echo "deploying" && openssl aes-256-cbc -K $encrypted_8658c7e4e38a_key -iv $encrypted_8658c7e4e38a_iv -in Houston-be1666ecca81.json.enc -out Houston-be1666ecca81.json -d'
